name: Check Upstream Release

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for updates and modify spec
        run: |
          chmod +x daily-update.sh
          ./daily-update.sh
